[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_err.log

[program:uvicorn]
command=uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers %(ENV_WORKERS)s --loop uvloop --access-log --log-level info
directory=/app
autostart=true
autorestart=true
environment=WORKERS="%(ENV_WORKERS)s"
stdout_logfile=/app/logs/uvicorn.log
stderr_logfile=/app/logs/uvicorn_err.log
