<script setup>
import { computed } from 'vue';
import { useRouter } from 'vue-router';
import { useEyeTestStore } from '../stores/useEyeTestStore';
import { AlertCircle, CheckCircle } from 'lucide-vue-next';

const router = useRouter();
const store = useEyeTestStore();

const gridSizePx = 340; // Fixed size nicely fitting mobile screens

const completeTest = (hasDistortion) => {
    store.saveResult('amslerGrid', { 
        hasDistortion, 
        score: hasDistortion ? 'Ijobiy (Muammo bor)' : 'Salbiy (Normal)',
        details: hasDistortion ? 'Chiziqlar qiyshiq yoki xira ko\'rindi' : 'Buzilishlar aniqlanmadi' 
    });
    router.push('/test/contrast');
};
</script>

<template>
  <div class="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4">
    <div class="max-w-2xl w-full bg-white rounded-3xl shadow-xl overflow-hidden">
        <div class="p-8 text-center">
            <h1 class="text-3xl font-extrabold text-slate-800 mb-4">Amsler Panjarasi</h1>
            <p class="text-slate-600 mb-8 max-w-lg mx-auto text-lg font-medium leading-relaxed">
                Makula degeneratsiyasini tekshirish.
                <br><b>Bir ko'zingizni yoping</b>, ikkinchisi bilan markaziy qora nuqtaga qarang (30-40 sm masofadan).
            </p>

            <div class="flex justify-center mb-8">
                <!-- Pure CSS Amsler Grid Implementation -->
                <div 
                    class="relative bg-white border border-slate-900 shadow-lg grid grid-cols-[repeat(20,1fr)] grid-rows-[repeat(20,1fr)]"
                    :style="{ width: gridSizePx + 'px', height: gridSizePx + 'px' }"
                >
                    
                    <!-- Center Dot -->
                    <div class="absolute inset-0 flex items-center justify-center pointer-events-none z-20">
                        <div class="w-2.5 h-2.5 bg-black rounded-full"></div>
                    </div>
                    
                    <!-- Grid Lines generated by v-for -->
                    <div v-for="i in 400" :key="i" class="border-[0.5px] border-black/80"></div>
                </div>
            </div>

            <h3 class="text-xl font-bold text-slate-800 mb-6">Markazga qaraganingizda, atrofdagi kataklar:</h3>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <button 
                    @click="completeTest(false)"
                    class="flex items-center justify-center gap-3 p-4 rounded-xl border-2 border-green-100 bg-green-50 text-green-700 hover:bg-green-100 hover:border-green-200 transition-all font-medium"
                >
                    <CheckCircle class="w-6 h-6" />
                    To'g'ri va aniq ko'rinyapti
                </button>
                
                <button 
                    @click="completeTest(true)"
                    class="flex items-center justify-center gap-3 p-4 rounded-xl border-2 border-red-100 bg-red-50 text-red-700 hover:bg-red-100 hover:border-red-200 transition-all font-medium"
                >
                    <AlertCircle class="w-6 h-6" />
                    Qiyshiq, to'lqinsimon yoki xira
                </button>
            </div>
        </div>
         <div class="bg-blue-50 p-4 text-center text-blue-700 text-sm">
             <span class="font-bold">Eslatma:</span> Agar ko'zoynak taqsangiz, uni yechmang.
        </div>
    </div>
  </div>
</template>
